### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [nkurinsky/SurveySim#4]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by nkurinsky** [comment]
Thanks for the advice, we have yet to have an official first-release but we will make this a priority, that's good to know. We're fairly new to this side of open-source.

**Comment by nkurinsky** [comment]
Easy enough, MIT license it is.
